services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
    networks:
      - tareasApp
    container_name: mongo-db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - tareasApp
    container_name: api-node

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - tareasApp
    container_name: web-client

networks:
  tareasApp:
    driver: bridge